apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-work-dir-volume
  namespace: spark
  labels:
    type: local
    app: spark
spec:
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  local:
    path: /run/desktop/mnt/host/c/kubernetes/storage/spark-work
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - minicube
                - 