apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server-deployment
  namespace: spark-namespace
  labels:
    app: spark-history-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      serviceAccountName: spark-service-account
      containers:
        - name: spark-history-server-container
          image: docker.io/apache/spark:latest
          command: [ "/opt/spark/sbin/start-history-server.sh" ]
          ports:
            - containerPort: 18080
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "1"
            - name: SPARK_PUBLIC_DNS
              value: "localhost"
            - name: SPARK_HISTORY_OPTS
              value: "-Dspark.history.fs.logDirectory=/mnt/spark-logs"
          volumeMounts:
            - name: spark-history-volume
              mountPath: /mnt/spark-logs
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: spark-history-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: spark-history-server-service
  namespace: spark-namespace
spec:
  type: LoadBalancer
  ports:
    - name: spark-history-ui
      port: 18080
      targetPort: 18080
  selector:
    app: spark-history-server
