apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-deployment
  namespace: spark-namespace
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      serviceAccountName: spark-service-account
      containers:
        - name: spark-leader-container
          image: docker.io/apache/spark:latest
          command: [ "/opt/spark/sbin/start-master.sh" ]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "1"
            - name: SPARK_PUBLIC_DNS
              value: "localhost"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
  namespace: spark-namespace
spec:
  type: LoadBalancer
  ports:
    - name: spark-master-rpc
      port: 7077
      targetPort: 7077
    - name: spark-master-ui
      port: 8080
      targetPort: 8080
  selector:
    app: spark-master
