apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-a-deployment
  namespace: spark-namespace
  labels:
    app: spark-worker-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-a
  template:
    metadata:
      labels:
        app: spark-worker-a
    spec:
      serviceAccountName: spark-service-account
      containers:
        - name: spark-worker-a-container
          image: docker.io/apache/spark:latest
          command: [ "/opt/spark/sbin/start-worker.sh" ]
          args: [ "spark://spark-master-service.spark-namespace.svc:7077" ]
          ports:
            - containerPort: 8081
          env:
            - name: SPARK_NO_DAEMONIZE
              value: "1"
            - name: SPARK_PUBLIC_DNS
              value: "localhost"
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8081"
            - name: SPARK_WORKER_CORES
              value: "4"
            - name: SPARK_WORKER_MEMORY
              value: "16G"
          resources:
            limits:
              memory: "16Gi"
              cpu: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-a-service
  namespace: spark-namespace
spec:
  type: LoadBalancer
  ports:
    - name: spark-worker-a-ui
      port: 8081
      targetPort: 8081
  selector:
    app: spark-worker-a
