apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-ssh-deployment
  namespace: spark-namespace
  labels:
    app: spark-ssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-ssh
  template:
    metadata:
      labels:
        app: spark-ssh
    spec:
      serviceAccountName: spark-service-account
      containers:
        - name: spark-ssh
          image: localhost/spark-ssh:1.0
          command: [ "/usr/sbin/sshd" ]
          args: [ "-D" ]
          ports:
            - containerPort: 22
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-ssh-service
  namespace: spark-namespace
spec:
  type: LoadBalancer
  ports:
    - name: spark-ssh-port
      protocol: TCP
      port: 8022
      targetPort: 22
  selector:
    app: spark-ssh
